package main

import (
	"bytes"
	"encoding/csv"
	"fmt"
	"go/format"
	"io"
	"os"
	"regexp"
	"strconv"
)

func genCS(r io.Reader, dst string) (c int, err error) {
	var (
		reBin = regexp.MustCompile(`^0x([0123456789ABCDEF]{2}),0x([0123456789ABCDEF]{2})$`)
		buf   bytes.Buffer
		names bytes.Buffer
		rec   []string
	)

	buf.Grow(4096)
	buf.Reset()
	names.Grow(4096)
	names.Reset()

	buf.WriteString("// Code generated by \"tlsvecgen\". DO NOT EDIT.\n")
	buf.WriteString("package tlsvector\n")
	buf.WriteString("var(__cs=map[CipherSuite]uint32{\n")

	rdr := csv.NewReader(r)
	for i := 0; ; i++ {
		rec, err = rdr.Read()
		if err == io.EOF {
			err = nil
			break
		}
		if err != nil {
			return
		}
		if i == 0 {
			// Skip header line.
			continue
		}

		if m := reBin.FindStringSubmatch(rec[0]); len(m) > 0 {
			if rec[1] == "Reserved" || rec[1] == "Unassigned" {
				continue
			}
			var key int64
			key, err = strconv.ParseInt(m[1]+m[2], 16, 64)
			if err != nil {
				return
			}
			lo := names.Len()
			names.WriteString(rec[1])
			hi := names.Len()
			enc := uint32(lo)<<16 | uint32(hi)
			buf.WriteString(fmt.Sprintf("0x%04x:0x%08x,\n", key, enc))
			c++
		}
	}
	buf.WriteString("}\n")
	buf.WriteString("__cs_buf=[]byte{\n")
	nb := names.Bytes()
	for i := 0; i < len(nb); i++ {
		if i > 0 && i%16 == 0 {
			_ = buf.WriteByte('\n')
		}
		_, _ = buf.WriteString(fmt.Sprintf("0x%02x, ", nb[i]))
	}

	buf.WriteString("\n}\n)\n")

	source := buf.Bytes()
	var fmtSource []byte
	if fmtSource, err = format.Source(source); err != nil {
		return
	}
	err = os.WriteFile(dst, fmtSource, 0644)

	return
}
