package main

import (
	"bytes"
	"encoding/csv"
	"fmt"
	"go/format"
	"io"
	"os"
	"strconv"
	"strings"
)

func genCCT(r io.Reader, dst string) (c int, err error) {
	var (
		rec   []string
		buf   bytes.Buffer
		names bytes.Buffer
		inits bytes.Buffer
	)

	buf.Grow(4096)
	buf.Reset()
	names.Grow(4096)
	names.Reset()
	inits.Grow(4096)
	inits.Reset()

	buf.WriteString("// Code generated by \"tlsvecgen\". DO NOT EDIT.\n")
	buf.WriteString("package tlsvector\n")
	buf.WriteString("import \"math\"\n")
	buf.WriteString("var(__cct [math.MaxUint8]uint32\n")

	rdr := csv.NewReader(r)
	for i := 0; ; i++ {
		rec, err = rdr.Read()
		if err == io.EOF {
			err = nil
			break
		}
		if err != nil {
			return
		}
		if i == 0 || rec[1] == "Unassigned" || strings.HasPrefix(rec[1], "Reserved") {
			// Skip header line or reserved lines.
			continue
		}

		var key int64
		key, err = strconv.ParseInt(rec[0], 10, 64)
		if err != nil {
			return
		}

		lo := names.Len()
		names.WriteString(rec[1])
		hi := names.Len()
		enc := uint32(lo)<<16 | uint32(hi)
		inits.WriteString(fmt.Sprintf("__cct[0x%04x]=0x%08x\n", key, enc))

		c++
	}

	buf.WriteString("__cct_buf=[]byte{\n")
	nb := names.Bytes()
	for i := 0; i < len(nb); i++ {
		if i > 0 && i%16 == 0 {
			_ = buf.WriteByte('\n')
		}
		_, _ = buf.WriteString(fmt.Sprintf("0x%02x, ", nb[i]))
	}

	buf.WriteString("\n}\n)\n")

	buf.WriteString("func init(){\n")
	buf.Write(inits.Bytes())
	buf.WriteString("}\n")

	source := buf.Bytes()
	var fmtSource []byte
	if fmtSource, err = format.Source(source); err != nil {
		return
	}
	err = os.WriteFile(dst, fmtSource, 0644)

	return
}
