package main

import (
	"bytes"
	"encoding/csv"
	"fmt"
	"go/format"
	"io"
	"os"
	"regexp"
	"strconv"
	"strings"

	"golang.org/x/text/cases"
	"golang.org/x/text/language"
)

func genExt(r io.Reader, dst string) (c int, err error) {
	var (
		rec   []string
		buf   bytes.Buffer
		names bytes.Buffer
		cnstr bytes.Buffer
	)

	buf.Grow(4096)
	buf.Reset()
	names.Grow(4096)
	names.Reset()
	cnstr.Grow(4096)
	cnstr.Reset()

	buf.WriteString("// Code generated by \"tlsvecgen\". DO NOT EDIT.\n")
	buf.WriteString("package tlsvector\n")
	buf.WriteString("var(__ext=map[ExtensionType]uint32{\n")

	rdr := csv.NewReader(r)
	for i := 0; ; i++ {
		rec, err = rdr.Read()
		if err == io.EOF {
			err = nil
			break
		}
		if err != nil {
			return
		}
		if i == 0 || rec[1] == "Unassigned" || strings.HasPrefix(rec[1], "Reserved") {
			// Skip header line or reserved/unassigned lines.
			continue
		}

		var key int64
		key, err = strconv.ParseInt(rec[0], 10, 64)
		if err != nil {
			return
		}

		lo := names.Len()
		names.WriteString(rec[1])
		hi := names.Len()
		enc := uint32(lo)<<16 | uint32(hi)
		buf.WriteString(fmt.Sprintf("0x%04x:0x%08x,\n", key, enc))

		name := rec[1]
		if pos := strings.IndexByte(name, '('); pos != -1 {
			name = name[:pos]
		}
		namew := strings.ReplaceAll(name, "_", " ")
		namew = cases.Title(language.English).String(namew)
		namew = reAcronymRepl.ReplaceAllStringFunc(namew, strings.ToUpper)
		fn := fmt.Sprintf("NewExtensionDescriptor%s", namew)
		fn = strings.ReplaceAll(fn, " ", "")
		cnstr.WriteString(fmt.Sprintf("0x%04x:%s,\n", key, fn))

		c++
	}

	buf.WriteString("}\n")

	buf.WriteString("__ext_descr=map[ExtensionType]func([]byte)ExtensionDescriptor{\n")
	buf.Write(cnstr.Bytes())
	buf.WriteString("}\n")

	buf.WriteString("__ext_buf=[]byte{\n")
	nb := names.Bytes()
	for i := 0; i < len(nb); i++ {
		if i > 0 && i%16 == 0 {
			_ = buf.WriteByte('\n')
		}
		_, _ = buf.WriteString(fmt.Sprintf("0x%02x, ", nb[i]))
	}

	buf.WriteString("\n}\n)\n")

	source := buf.Bytes()
	var fmtSource []byte
	if fmtSource, err = format.Source(source); err != nil {
		return
	}
	err = os.WriteFile(dst, fmtSource, 0644)

	return
}

var reAcronymRepl = regexp.MustCompile(`(?i)\b(Url|Ca|Hmac|Ec|Srp|Srtp|Mac|Tls|Lts|Psk|Tlmsp|Ekt|Oid|Id|Quic|Dnssec|Rrc|Ech|Pwd)\b`)
