package main

import (
	"bytes"
	"encoding/csv"
	"flag"
	"fmt"
	"go/format"
	"io"
	"log"
	"net/http"
	"os"
	"regexp"
	"strconv"
)

var ianaCS, ianaExt, dst string

func init() {
	flag.StringVar(&ianaCS, "cipher-suites", "", "Full URL to IANA source CSV with supported TLS cipher suites.")
	flag.StringVar(&ianaExt, "extensions", "", "Full URL to IANA source CSV with supported TLS extensions.")
	flag.StringVar(&dst, "dst", "", "Path to destination Go file.")
	flag.Parse()
	if len(ianaCS) == 0 && len(ianaExt) == 0 {
		log.Fatalln("empty source URL provided")
	}
	if len(dst) == 0 {
		log.Fatalln("empty destination path provided")
	}
}

func main() {
	resp, err := http.Get(ianaCS)
	if err != nil {
		log.Fatalln(err)
	}
	defer func() { _ = resp.Body.Close() }()

	var (
		unit string
		c    int
	)
	switch {
	case len(ianaCS) > 0:
		unit = "cipher suites"
		c, err = genCS(resp.Body, dst)
	case len(ianaExt) > 0:
		unit = "extensions"
		c, err = genExt(resp.Body, dst)
	}

	log.Printf("%d %s writes to %s\n", c, unit, dst)
}

func genCS(r io.Reader, dst string) (c int, err error) {
	var (
		reBin = regexp.MustCompile(`^0x([0123456789ABCDEF]{2}),0x([0123456789ABCDEF]{2})$`)
		buf   bytes.Buffer
		names bytes.Buffer
	)

	names.Grow(4096)
	names.Reset()

	buf.WriteString("// Code generated by \"tlsvecgen\". DO NOT EDIT.\n")
	buf.WriteString("package tlsvector\n")
	buf.WriteString("var(__cs=map[CipherSuite]uint32{\n")

	rdr := csv.NewReader(r)
	for i := 0; ; i++ {
		rec, err := rdr.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			log.Fatalln(err)
		}
		if i == 0 {
			// Skip header line.
			continue
		}

		if m := reBin.FindStringSubmatch(rec[0]); len(m) > 0 {
			if rec[1] == "Reserved" || rec[1] == "Unassigned" {
				continue
			}
			key, err := strconv.ParseInt(m[1]+m[2], 16, 64)
			if err != nil {
				log.Fatalln(err)
			}
			lo := names.Len()
			names.WriteString(rec[1])
			hi := names.Len()
			enc := uint32(lo)<<16 | uint32(hi)
			buf.WriteString(fmt.Sprintf("0x%04x:0x%04x,\n", key, enc))
			c++
		}
	}
	buf.WriteString("}\n")
	buf.WriteString("__cs_buf=[]byte{\n")
	nb := names.Bytes()
	for i := 0; i < len(nb); i++ {
		if i > 0 && i%16 == 0 {
			_ = buf.WriteByte('\n')
		}
		_, _ = buf.WriteString(fmt.Sprintf("0x%02x, ", nb[i]))
	}

	buf.WriteString("\n}\n)\n")

	source := buf.Bytes()
	var fmtSource []byte
	if fmtSource, err = format.Source(source); err != nil {
		return
	}
	err = os.WriteFile(dst, fmtSource, 0644)

	return
}

func genExt(r io.Reader, dst string) (c int, err error) {
	// todo implement me
	return
}
